### ISSUE TITLE
Requirements installation fails

### ISSUE THREAD

**Issue by bondjimbond** [uml-digitalinitiatives/multipage_to_book_batch_converter#1]
Tried installing from the requirements file, but failing here:

```
vagrant@islandora:~/multipage_to_book_batch_converter$ pip install -r requirements.txt
Downloading/unpacking Pillow>=6.2.1 (from -r requirements.txt (line 1))
  Downloading Pillow-7.2.0.tar.gz (39.1MB): 39.1MB downloaded
  Running setup.py (path:/tmp/pip_build_vagrant/Pillow/setup.py) egg_info for package Pillow
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_vagrant/Pillow/setup.py", line 305
        yield from self.features
                 ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_vagrant/Pillow/setup.py", line 305

    yield from self.features

             ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_vagrant/Pillow
Storing debug log for failure in /home/vagrant/.pip/pip.log
```

Any idea what's wrong?

**Comment by whikloj** [comment]
Python version?

**Comment by whikloj** [comment]
```
> python --version
Python 3.7.5

> pip install -r requirements.txt 
Collecting Pillow>=6.2.1
  Downloading Pillow-7.2.0-cp37-cp37m-macosx_10_10_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 737 kB/s 
Processing /Users/whikloj/Library/Caches/pip/wheels/76/5c/8c/353757ed239e32a74851851d7ae022f9cf4c1f1c82d2bb94af/reportlab-3.3.0-cp37-cp37m-macosx_10_14_x86_64.whl
Processing /Users/whikloj/Library/Caches/pip/wheels/53/84/19/35bc977c8bf5f0c23a8a011aa958acd4da4bbd7a229315c1b7/PyPDF2-1.26.0-cp37-none-any.whl
Collecting lxml>=3.5.0
  Downloading lxml-4.5.2-cp37-cp37m-macosx_10_9_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 1.7 MB/s 
Requirement already satisfied: setuptools>=2.2 in /Users/whikloj/www/DAM/multi/lib/python3.7/site-packages (from reportlab==3.3.0->-r requirements.txt (line 2)) (49.6.0)
Requirement already satisfied: pip>=1.4.1 in /Users/whikloj/www/DAM/multi/lib/python3.7/site-packages (from reportlab==3.3.0->-r requirements.txt (line 2)) (20.2.2)
Installing collected packages: Pillow, reportlab, pyPDF2, lxml
Successfully installed Pillow-7.2.0 lxml-4.5.2 pyPDF2-1.26.0 reportlab-3.3.0
```

**Comment by bondjimbond** [comment]
Yeah, it's looking like problems with Python 2.7.5, which is prepackaged in the Vagrant machine. Annoyingly, I can't seem to get it to use a later version, even though it's installed, so it's gonna be a bit of a slog to test this.

**Comment by bondjimbond** [comment]
Dang it. I managed to get both python3 and pip3 running, but still erroring:

```
$ sudo pip3 install -r requirements.txt
Downloading/unpacking Pillow>=6.2.1 (from -r requirements.txt (line 1))
  Downloading Pillow-7.2.0.tar.gz (39.1MB): 39.1MB downloaded
  Running setup.py (path:/tmp/pip_build_root/Pillow/setup.py) egg_info for package Pillow
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/Pillow/setup.py", line 903, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW),
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 186, in find_sources
        mm.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 246, in run
        self.add_defaults()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 282, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 179, in add_defaults
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip_build_root/Pillow/setup.py", line 333, in finalize_options
        if not self.parallel:
      File "/usr/lib/python3.4/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: parallel
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/Pillow.egg-info

writing dependency_links to pip-egg-info/Pillow.egg-info/dependency_links.txt

writing top-level names to pip-egg-info/Pillow.egg-info/top_level.txt

writing pip-egg-info/Pillow.egg-info/PKG-INFO

writing manifest file 'pip-egg-info/Pillow.egg-info/SOURCES.txt'

/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'

  warnings.warn(msg)

/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'project_urls'

  warnings.warn(msg)

warning: manifest_maker: standard file '-c' not found



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/Pillow/setup.py", line 903, in <module>

    zip_safe=not (debug_build() or PLATFORM_MINGW),

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "<string>", line 15, in replacement_run

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 186, in find_sources

    mm.run()

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 246, in run

    self.add_defaults()

  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 282, in add_defaults

    sdist.add_defaults(self)

  File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 179, in add_defaults

    build_ext = self.get_finalized_command('build_ext')

  File "/usr/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command

    cmd_obj.ensure_finalized()

  File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized

    self.finalize_options()

  File "/tmp/pip_build_root/Pillow/setup.py", line 333, in finalize_options

    if not self.parallel:

  File "/usr/lib/python3.4/distutils/cmd.py", line 103, in __getattr__

    raise AttributeError(attr)

AttributeError: parallel

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/Pillow
Storing debug log for failure in /home/vagrant/.pip/pip.log

```

**Comment by bondjimbond** [comment]
For the record:
- Requires Python 3+
- Requires Pip 3+
